### PR TITLE
fix: add epoch timestamp parsing for token validity checks

### LINKED ISSUE #73: fix: check expiresAt is epoch seconds
expiresAt will accept epoch milliseconds and still mint the token, but then these tokens are not compatible with nuc-py; the lib should enforce epoch seconds when constructing the token

### PR DESCRIPTION
**Pull request by pablojhl**
closes #73

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -13,6 +13,26 @@ export const HexSchema = z.string().regex(/^[a-fA-F0-9]+$/, "invalid hex");
 /** Type for a validated hexadecimal string. */
 export type Hex = z.infer<typeof HexSchema>;
 
+/**
+ * Epoch timestamp in seconds.
+ **/
+const EpochSeconds = z.number().int().max(1e12);
```
Comment (tim-hm) [inline src/utils.ts:19]: Can we use this for decoding tokens as well?

**Review by tim-hm — CHANGES_REQUESTED** [review]

File: src/utils.ts [hunk 2]
```diff
@@ -13,6 +13,26 @@ export const HexSchema = z.string().regex(/^[a-fA-F0-9]+$/, "invalid hex");
...
+ * Throws a ZodError if validation fails.
+ *
+ * @param value - The value to parse as epoch seconds.
+ * @returns The parsed epoch seconds as a number.
+ * @throws ZodError if the value is not a valid epoch timestamp.
+ * @example
+ * parseEpochSeconds(1633036800) // Returns 1633036800
+ * parseEpochSeconds("invalid") // Throws ZodError
+ */
+export const parseEpochSeconds = (value: unknown): number =>
```
Comment (jcabrero) [inline src/utils.ts:33]: I'm not sure what the TS way of handling errors is, but would it make sense to catch that error and send a more verbose message to the user so that he knows what is happening? It doesn't seem obvious to me that a user having this error will know this is the wrong timestamp.

File: src/utils.ts (hunk 1 above)
Comment (pablojhl) [reply src/utils.ts]: Done

File: src/utils.ts (hunk 2 above)
Comment (pablojhl) [reply src/utils.ts]: Done
